# Generated by Django 5.1.6 on 2025-04-01 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BEPEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('annee_examen', models.CharField(max_length=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classe')),
            ],
        ),
        migrations.CreateModel(
            name='CorrigeBEPEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fichier_pdf', models.FileField(upload_to='corriges_bepec_pdfs/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corriges_bepec', to=settings.AUTH_USER_MODEL)),
                ('bepec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corriges', to='api.bepec')),
            ],
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fichier_pdf', models.FileField(upload_to='devoirs_pdfs/')),
                ('date', models.DateField()),
                ('annee', models.CharField(max_length=4)),
                ('categorie', models.CharField(choices=[('classe', 'Devoir de classe'), ('departemental', 'Devoir départemental'), ('composition', 'Composition')], max_length=20)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='api.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs_composes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Corrige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fichier_pdf', models.FileField(upload_to='corriges_pdfs/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corriges', to=settings.AUTH_USER_MODEL)),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corriges', to='api.devoir')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fichier_pdf', models.FileField(upload_to='documents_pdfs/')),
                ('categorie', models.CharField(choices=[('guides', 'Guides'), ('livres', 'Livres au programme'), ('pedagogiques', 'Fichiers pédagogiques'), ('autres', 'Autres')], max_length=20)),
                ('date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to=settings.AUTH_USER_MODEL)),
                ('classes', models.ManyToManyField(related_name='matieres', to='api.classe')),
            ],
        ),
        migrations.AddField(
            model_name='devoir',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='api.matiere'),
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('fichier_pdf', models.FileField(upload_to='chapitres_pdfs/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='api.matiere')),
            ],
        ),
        migrations.AddField(
            model_name='bepec',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.matiere'),
        ),
    ]
