# Generated by Django 5.1.6 on 2025-05-08 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['nom'], 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ['nom'], 'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.AlterField(
            model_name='classe',
            name='author',
            field=models.ForeignKey(help_text='Enseignant qui a créé cette classe', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(help_text='Ex: 6ème A, 5ème B, etc.', max_length=50, verbose_name='Nom de la classe'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='author',
            field=models.ForeignKey(help_text='Enseignant qui a créé cette matière', on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='classes',
            field=models.ManyToManyField(help_text='Sélectionnez les classes pour cette matière', related_name='matieres', to='api.classe', verbose_name='Classes concernées'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='nom',
            field=models.CharField(help_text='Ex: Mathématiques, Français, etc.', max_length=50, verbose_name='Nom de la matière'),
        ),
    ]
